{% set version = "1.4.6" %}

package:
  name: pyhum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyHum/PyHum-{{ version }}.tar.gz
  sha256: 58032ba3383334f40142750a4ea472d5b450476d989df9d614e63964b49a4b68

build:
  number: 1001
  skip: True  # [py3k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pillow
    - matplotlib
    - pyproj
    - scikit-image
    - simplekml
    - joblib
    - basemap
    - scikit-learn
    - pyresample
    - dask
    - toolz
    - pandas

test:
  imports:
    - PyHum

about:
  home: https://github.com/dbuscombe-usgs/PyHum
  license: LGPL-3.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Python/Cython scripts to read Humminbird DAT.'

extra:
  recipe-maintainers:
    - dbuscombe-usgs
    - ocefpaf
