{% set version = "1.3.19" %}

package:
  name: pyhum
  version: {{ version }}

source:
  fn: PyHum-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/PyHum/PyHum-{{ version }}.tar.gz
  sha256: 2b884dab5d200175f7eb2011e7fe395aa23e2b3dceef704601a45af112b831d5

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install

requirements:
  build:
    - python
    - cython
    - numpy x.x
  run:
    - python
    - numpy x.x
    - scipy
    - pillow
    - matplotlib
    - pyproj
    - scikit-image
    - simplekml
    - joblib
    - basemap
    - scikit-learn
    - pyresample
    - dask
    - toolz
    - pandas

test:
  imports:
    - PyHum
  commands:
    - conda inspect linkages -p $PREFIX pyhum  # [not win]
    - conda inspect objects -p $PREFIX pyhum  # [osx]

about:
  home: https://github.com/dbuscombe-usgs/PyHum
  license: LGPL-3.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Python/Cython scripts to read Humminbird DAT.'

extra:
  recipe-maintainers:
    - dbuscombe-usgs
    - ocefpaf
