travis:
  secure:
    BINSTAR_TOKEN: ldLpQjANruD29siv9SrfQ0JIKhYQz5VMTVd6xk1K594hFCNSWwHep8I4jOsUmwab6c058UPPIjT/NOYADobvjcU//tq334oTSOXl0T4zr0l+CM2yCHHNObmU96xx44jjSKJoVoGNIMdS9XFKmwym/lR2QvlwDxHXDtL1fVn9Cd40FvcqahsEZFSsjOhx29v+ZoskCkXYeZU0PpZD8Gt+UvGZgxHrW3rEt0+zyq5HjmY+GNtyl8osuGICs4hWD55y9a1dmHFl4dNCmKrIp2LTNC5OhzNspVDVZm2nGRLcBeUnQ/kUVPWL6nHD/sielerQDwGNHZUQITNntE9j+TI3zwqOv349nZB8S8jc/GSo8BxJL6zGEZh3JFHIhnF1SCl9sepiXx5SEr8w7DnutR9Vhfw5o9cIETIqPs1hoAxYtIU3AxaTid7RAmUmtmZRgu9XvjOLcRw+y2eEQtIDjRU8WAXOJd1H3OuEjgPRVuAF5fVreIk1PIfCuKMd4tKg9XEy94HzbvNYQMNufD9GwudI1TdDrKLiySZuZZWMzU20eUBjHCYyQ1ujZbGeRx7PZ6xQ3iVaRZBDoU0nbZoXzuvtqje5VISdbDImambk0wDCzPWwe/UXlEvCi4f6aT7DJEYfz3thovehgWIbdJEzcvg1RVoq+ke9q9e8Ag5TWS5UOdo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
