travis:
  secure:
    BINSTAR_TOKEN: cJ60UjTSfPVrX7piQoOFj3GhwOKlcini1V1W/MFf3Y8l/NFG0+BgsMkFOSnjjwUseXr7V5xtGccutqfLTLVTjw+6n+kuvGYrDzSx/nV5cIgps/YwlHuLV0P6xeYdeFcb5+k5sP0Sow0m8cbc6eBbtFAA4Hpf1rAjCJzrVHk9+La62kIq7I8yBd1nCflou/rb9W4d/TSzi3ev+p/hjF5Edyo5aiO0BuuVXPr/8nvTZxFavgHTD5VSI/N0lGXt2N1qzkx8Lzo0dYtbzJsvMuOp/g8DEHAHNgpx7hNlu+k7CtH3OKdIrSMOGO7463K0KVAwPN4q56ETqlDszH9TFb7zEfur9PpuQ+Yv6ZCSCbdHApt0ZeWC5hfYtba21ECJTL8tZmDvw54jI0+wi96PSs3fnAsHnviP6FkgDED5MKlvkTUwa/ekpvm6ryPBIfKmzvVFRzciRxxWwjtvYBSUsvQoXnys7e3/xCBzb/KKY8x6RpHvENWXTrMq6wFptEOeK6w9CU3C3ALej3i3M/EuaY0qPjZC8Tg7g/aEN3NSCcP5eOGbZvJU4lx8itDOIz5Iw9qh2mvjmsUqAWEskde/jbOTQOoZbZE6M0igaw86TCyLn0mdBrzQ6259NzeuymGUi2hfPTVQ8rHfpyLQL8VMFroLEQVzmcd30kdf6cRlHF6+o9g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
